### ISSUE TITLE
consulta friki

### ISSUE THREAD

**Issue by matiasHoz** [pdepjm/2024-tp0-presentacion-lDevecchi#2]
terrible presentación! Ya que veo que te gusta la ciencia ficción, necesito saber tu opinión de Dune Part 2, leíste la novela? Saludos.

**Comment by lDevecchi** [comment]
Gracias loco! A Dune lo planeo leer a finales de año o 2025. No conozco ni el nombre del prota, pero le quiero dedicar el tiempo que se merece porque me han dicho que es tremenda. Saludos!
